# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
dist: xenial
cache: packages
latex: false
fortran: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install curl
        - brew link --force curl

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev gfortran
  - R -q -e "install.packages('udunits2',configure.args='--with-udunits2-include=/usr/include/udunits2')"
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov(branch = "master")'

notifications:
  email:
  on_success: change
on_failure: change

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'